spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
  activemq:
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
    packages:
      trust-all: true
  jms:
    client-id: workload-service
    listener:
      auto-startup: true
      session:
        acknowledge-mode: auto

logging:
  level:
    root: DEBUG