spring:
  datasource:
    url: jdbc:h2:file:./data/gym-crm-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    client-id: core-service
    listener:
      auto-startup: true
      session:
        acknowledge-mode: auto
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.gcs.app: DEBUG